language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
on:
  branch: master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
