language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
  - git add .
  - git commit -m "build: travis-ci"
  - git push origin master
on:
  branch: master
