language: node_js
node_js:
	- "stable"
cache:
	directories:
		- node_modules
before_script:
	- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
	- export PATH="$HOME/.yarn/bin:$PATH"
install:
	- yarn
script:
	- yarn lint
	- yarn test
	- yarn build
on:
  branch: master